# Persistence
spring.jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true

spring.datasource.url: jdbc:h2:file:~/h2-file-db/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;
