# Persistence
spring.jpa:
  hibernate:
    ddl-auto: create-drop
  properties:
    hibernate:
      show_sql: true

spring.datasource.url: jdbc:h2:file:~/h2-file-db/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;

# RabbitMQ
multiplication.exchange: multiplication_exchange
multiplication.solved.key: multiplication.solved
